version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "9000:9000" 

  webserver:
    image: nginx:latest # O utiliza una imagen de Apache
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Archivo de configuración de Nginx
    ports:
      - "80:80" # Puerto de Nginx

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432" 